name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Setup Python
      uses: actions/setup-python@v2

    - uses: actions/checkout@v2
    - name: make
      run: make INC=/usr/share/local/boost
    - name: make test
      run: make test
