on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: 'sibyl-bot'
        SLACK_FOOTER: ''
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: 'https://github.com/sibyl-team/sib/blob/master/examples/figs/sibbot.jpg'
